apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-app-dev
  namespace: argocd
  annotations:
    description: "Development environment namespace"
spec:
  project: default
  source:
    repoURL: https://github.com/kk2130aamountain-lgtm/apps.git
    targetRevision: main
    path: overlays/dev
  destination:
    server: https://127.0.0.1:37391
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
